# Generated by Django 4.1.4 on 2022-12-25 12:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follwed_by',
            new_name='followed_by',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('followed_by', 'following')},
        ),
    ]
